### ISSUE TITLE
custom key for renderItem

### ISSUE THREAD

**Issue by bougieL** [jobtoday/react-native-image-viewing#60]
The duplicated key warning will show when uri duplicated

**Comment by joonhocho** [comment]
Having the same issuse

**Comment by CarlOmega** [comment]
Line 56 of the ImageViewing.js ```keyExtractor={(imageSrc) => imageSrc.uri || `${imageSrc}`}``` is the culprit. 
You can get around this by setting it to something else I use a property on my object called `name` which is a unique filename using a timestamp. 

This mainly happens when the url/uri is the same or it is the same file. This causes major inefficiency if using uri of base64 since the keys are compared to each other leading to slower load times. A remedy for this would to allow developers to use custom keyextractors or use a uuid generator.

**Comment by rajeshde** [comment]
@CarlOmega  Submitted a PR #105  implementing custom keyExtractor. I hope this will solve this issue. Would like to hear from maintainers.
